import type {
  Category,
  Dish,
  MenuDocument,
  ModifierGroup,
} from "@/types/catalog";

/**
 * The India Gate menu.
 *
 * This is the seed the `LocalMenuRepository` serves. It is deliberately a
 * typed module rather than JSON: the compiler catches a dish pointing at a
 * modifier group that does not exist, or a category slug that was renamed —
 * mistakes that JSON would happily ship to production.
 *
 * Prices are in SGD cents, GST-inclusive, which is how menus are quoted in
 * Singapore.
 */

export const CATEGORIES: Category[] = [
  {
    id: "cat-tiffins",
    slug: "tiffins",
    name: "Tiffins",
    tagline: "Dosai, idli and vadai, off the griddle all day",
    icon: "Soup",
    sortOrder: 0,
  },
  {
    id: "cat-biryani",
    slug: "biryani",
    name: "Hyderabadi Biryani",
    tagline: "Sealed dum, aged basmati, cooked to order",
    icon: "Flame",
    sortOrder: 1,
  },
  {
    id: "cat-curries",
    slug: "curries",
    name: "Curries",
    tagline: "Chettinad, Malabar and Andhra house gravies",
    icon: "CookingPot",
    sortOrder: 2,
  },
  {
    id: "cat-breads",
    slug: "breads",
    name: "Breads & Rice",
    tagline: "Naan, paratha, appam and steamed rice",
    icon: "Wheat",
    sortOrder: 3,
  },
  {
    id: "cat-desserts",
    slug: "desserts",
    name: "Desserts",
    tagline: "Payasam, mysore pak and kesari, made fresh daily",
    icon: "IceCream2",
    sortOrder: 4,
  },
  {
    id: "cat-beverages",
    slug: "beverages",
    name: "Beverages",
    tagline: "Filter kaapi, lassi and cooling drinks",
    icon: "CupSoda",
    sortOrder: 5,
  },
];

export const MODIFIER_GROUPS: ModifierGroup[] = [
  {
    id: "mg-spice",
    name: "Spice level",
    description: "Our kitchen adjusts the chilli, never the flavour.",
    selectionType: "SINGLE",
    isRequired: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { id: "opt-spice-mild", name: "Mild", description: "Gentle warmth", priceDeltaCents: 0, isDefault: false, isAvailable: true },
      { id: "opt-spice-medium", name: "Medium", description: "How we serve it in-house", priceDeltaCents: 0, isDefault: true, isAvailable: true },
      { id: "opt-spice-spicy", name: "Spicy", description: "A proper kick", priceDeltaCents: 0, isDefault: false, isAvailable: true },
      { id: "opt-spice-extra", name: "Extra spicy", description: "Guntur chilli, no mercy", priceDeltaCents: 0, isDefault: false, isAvailable: true },
    ],
  },
  {
    id: "mg-dosa-prep",
    name: "Preparation",
    selectionType: "SINGLE",
    isRequired: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { id: "opt-prep-classic", name: "Classic", priceDeltaCents: 0, isDefault: true, isAvailable: true },
      { id: "opt-prep-crispy", name: "Extra crispy", description: "Cooked a minute longer", priceDeltaCents: 0, isDefault: false, isAvailable: true },
      { id: "opt-prep-ghee", name: "Ghee roast", description: "Finished in clarified butter", priceDeltaCents: 180, isDefault: false, isAvailable: true, dietaryType: "VEG" },
      { id: "opt-prep-butter", name: "Butter roast", priceDeltaCents: 150, isDefault: false, isAvailable: true, dietaryType: "VEG" },
    ],
  },
  {
    id: "mg-chutney",
    name: "Chutneys",
    description: "Choose up to three. Coconut and sambar come as standard.",
    selectionType: "MULTI",
    isRequired: false,
    minSelections: 0,
    maxSelections: 3,
    options: [
      { id: "opt-chut-coconut", name: "Extra coconut chutney", priceDeltaCents: 120, isDefault: false, isAvailable: true, dietaryType: "VEG" },
      { id: "opt-chut-tomato", name: "Tomato chutney", priceDeltaCents: 120, isDefault: false, isAvailable: true, dietaryType: "VEG" },
      { id: "opt-chut-mint", name: "Mint & coriander chutney", priceDeltaCents: 120, isDefault: false, isAvailable: true, dietaryType: "VEG" },
      { id: "opt-chut-podi", name: "Idli podi with gingelly oil", description: "Gunpowder", priceDeltaCents: 150, isDefault: false, isAvailable: true, dietaryType: "VEG" },
    ],
  },
  {
    id: "mg-tiffin-extras",
    name: "Extras",
    selectionType: "MULTI",
    isRequired: false,
    minSelections: 0,
    maxSelections: 2,
    options: [
      { id: "opt-extra-sambar", name: "Extra sambar", priceDeltaCents: 150, isDefault: false, isAvailable: true, dietaryType: "VEG" },
      { id: "opt-extra-rasam", name: "Extra rasam", priceDeltaCents: 150, isDefault: false, isAvailable: true, dietaryType: "VEG" },
      { id: "opt-extra-ghee", name: "Spoon of ghee", priceDeltaCents: 100, isDefault: false, isAvailable: true, dietaryType: "VEG" },
    ],
  },
  {
    id: "mg-biryani-portion",
    name: "Portion",
    selectionType: "SINGLE",
    isRequired: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { id: "opt-por-single", name: "Single", description: "Serves one", priceDeltaCents: 0, isDefault: true, isAvailable: true },
      { id: "opt-por-family", name: "Family handi", description: "Serves three to four", priceDeltaCents: 2600, isDefault: false, isAvailable: true },
    ],
  },
  {
    id: "mg-biryani-sides",
    name: "Accompaniments",
    description: "Raita and salan are included. Add more if you like.",
    selectionType: "MULTI",
    isRequired: false,
    minSelections: 0,
    maxSelections: 3,
    options: [
      { id: "opt-side-raita", name: "Extra raita", priceDeltaCents: 150, isDefault: false, isAvailable: true, dietaryType: "VEG" },
      { id: "opt-side-salan", name: "Extra mirchi ka salan", priceDeltaCents: 200, isDefault: false, isAvailable: true, dietaryType: "VEG" },
      { id: "opt-side-egg", name: "Boiled egg", priceDeltaCents: 150, isDefault: false, isAvailable: true, dietaryType: "EGG" },
      { id: "opt-side-gravy", name: "Extra dum gravy", priceDeltaCents: 180, isDefault: false, isAvailable: true },
    ],
  },
  {
    id: "mg-curry-portion",
    name: "Portion",
    selectionType: "SINGLE",
    isRequired: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { id: "opt-cpor-regular", name: "Regular", description: "Serves one to two", priceDeltaCents: 0, isDefault: true, isAvailable: true },
      { id: "opt-cpor-large", name: "Large", description: "Serves three", priceDeltaCents: 1900, isDefault: false, isAvailable: true },
    ],
  },
  {
    id: "mg-curry-side",
    name: "Make it a meal",
    selectionType: "MULTI",
    isRequired: false,
    minSelections: 0,
    maxSelections: 3,
    options: [
      { id: "opt-meal-rice", name: "Steamed basmati", priceDeltaCents: 250, isDefault: false, isAvailable: true, dietaryType: "VEG" },
      { id: "opt-meal-ghee-rice", name: "Ghee rice", priceDeltaCents: 350, isDefault: false, isAvailable: true, dietaryType: "VEG" },
      { id: "opt-meal-paratha", name: "Malabar paratha ×2", priceDeltaCents: 340, isDefault: false, isAvailable: true, dietaryType: "VEG" },
      { id: "opt-meal-appam", name: "Appam ×2", priceDeltaCents: 320, isDefault: false, isAvailable: true, dietaryType: "VEG" },
    ],
  },
  {
    id: "mg-sweetness",
    name: "Sweetness",
    selectionType: "SINGLE",
    isRequired: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { id: "opt-sweet-less", name: "Less sweet", priceDeltaCents: 0, isDefault: false, isAvailable: true },
      { id: "opt-sweet-normal", name: "As it comes", priceDeltaCents: 0, isDefault: true, isAvailable: true },
      { id: "opt-sweet-extra", name: "Extra sweet", priceDeltaCents: 0, isDefault: false, isAvailable: true },
    ],
  },
  {
    id: "mg-bread-qty",
    name: "Quantity",
    selectionType: "SINGLE",
    isRequired: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { id: "opt-bq-1", name: "1 piece", priceDeltaCents: 0, isDefault: true, isAvailable: true },
      { id: "opt-bq-2", name: "2 pieces", priceDeltaCents: 320, isDefault: false, isAvailable: true },
      { id: "opt-bq-4", name: "4 pieces", priceDeltaCents: 940, isDefault: false, isAvailable: true },
    ],
  },
];

/** Shorthand so the dish list below stays readable. */
const TIFFIN_MODS = ["mg-dosa-prep", "mg-spice", "mg-chutney", "mg-tiffin-extras"];
const BIRYANI_MODS = ["mg-biryani-portion", "mg-spice", "mg-biryani-sides"];
const CURRY_MODS = ["mg-curry-portion", "mg-spice", "mg-curry-side"];

export const DISHES: Dish[] = [
  // ---------------------------------------------------------------- Tiffins
  {
    id: "dish-masala-dosa",
    slug: "masala-dosa",
    name: "Masala Dosa",
    shortDescription: "Fermented rice crêpe, spiced potato, coconut chutney",
    description:
      "Batter ground fresh each morning and rested overnight, spread thin on a seasoned cast-iron tawa. Filled with turmeric potato tempered with mustard seed and curry leaf. Served with sambar and coconut chutney.",
    categorySlug: "tiffins",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "MILD",
    tags: ["BESTSELLER", "JAIN_AVAILABLE"],
    basePriceCents: 890,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 387,
    allergens: ["Mustard"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: TIFFIN_MODS,
    sortOrder: 0,
    rating: { average: 4.8, count: 412 },
  },
  {
    id: "dish-ghee-roast-dosa",
    slug: "ghee-roast-dosa",
    name: "Ghee Roast Dosa",
    shortDescription: "Extra-thin, lacquered in clarified butter",
    description:
      "Rolled long and crisp, brushed generously with house-clarified ghee until the edges shatter. Nothing inside — this one is about the crêpe.",
    categorySlug: "tiffins",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: ["CHEFS_SPECIAL", "CONTAINS_DAIRY"],
    basePriceCents: 1050,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 441,
    allergens: ["Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: TIFFIN_MODS,
    sortOrder: 1,
    rating: { average: 4.9, count: 268 },
  },
  {
    id: "dish-idli",
    slug: "idli-sambar",
    name: "Idli Sambar",
    shortDescription: "Three steamed rice cakes, lentil sambar, two chutneys",
    description:
      "Steamed in traditional moulds to order, so they arrive pillowy rather than dense. Sambar is simmered with drumstick, pumpkin and tamarind.",
    categorySlug: "tiffins",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "MILD",
    tags: ["BESTSELLER", "GLUTEN_FREE"],
    basePriceCents: 650,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 232,
    allergens: [],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-spice", "mg-chutney", "mg-tiffin-extras"],
    sortOrder: 2,
    rating: { average: 4.7, count: 356 },
  },
  {
    id: "dish-medu-vada",
    slug: "medu-vada",
    name: "Medu Vada",
    shortDescription: "Three urad dal doughnuts, crisp outside, airy within",
    description:
      "Batter whipped by hand until it floats, shaped and fried to order. Peppercorn, ginger and curry leaf throughout.",
    categorySlug: "tiffins",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "MILD",
    tags: ["GLUTEN_FREE"],
    basePriceCents: 690,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 298,
    allergens: [],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-spice", "mg-chutney", "mg-tiffin-extras"],
    sortOrder: 3,
    rating: { average: 4.6, count: 201 },
  },
  {
    id: "dish-ven-pongal",
    slug: "ven-pongal",
    name: "Ven Pongal",
    shortDescription: "Rice and moong dal, black pepper, cashew, ghee",
    description:
      "Slow-cooked to a soft, savoury porridge, finished with a tempering of whole peppercorn, cumin, cashew and curry leaf in ghee.",
    categorySlug: "tiffins",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "MILD",
    tags: ["CONTAINS_NUTS", "CONTAINS_DAIRY"],
    basePriceCents: 850,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 412,
    allergens: ["Cashew", "Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-spice", "mg-chutney", "mg-tiffin-extras"],
    sortOrder: 4,
    rating: { average: 4.5, count: 143 },
  },
  {
    id: "dish-rava-dosa",
    slug: "rava-dosa",
    name: "Onion Rava Dosa",
    shortDescription: "Lacy semolina crêpe, onion, green chilli, cumin",
    description:
      "Poured rather than spread, so it sets into a lace of holes. Studded with sliced onion and green chilli.",
    categorySlug: "tiffins",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "MEDIUM",
    tags: [],
    basePriceCents: 990,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 356,
    allergens: ["Gluten"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: TIFFIN_MODS,
    sortOrder: 5,
    rating: { average: 4.6, count: 187 },
  },
  {
    id: "dish-uttapam",
    slug: "onion-tomato-uttapam",
    name: "Onion Tomato Uttapam",
    shortDescription: "Thick pancake, griddled with onion and tomato",
    description:
      "The same batter as the dosa, poured thick and cooked slowly so the base caramelises while the top stays soft.",
    categorySlug: "tiffins",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "MILD",
    tags: [],
    basePriceCents: 950,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 374,
    allergens: [],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-spice", "mg-chutney", "mg-tiffin-extras"],
    sortOrder: 6,
    rating: { average: 4.4, count: 96 },
  },
  {
    id: "dish-poori-masala",
    slug: "poori-masala",
    name: "Poori Masala",
    shortDescription: "Two puffed breads, turmeric potato masala",
    description:
      "Fried to order so they arrive still inflated. The masala is looser than the dosa filling, closer to a light curry.",
    categorySlug: "tiffins",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "MILD",
    tags: [],
    basePriceCents: 890,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 468,
    allergens: ["Gluten"],
    isAvailable: false,
    unavailableUntilLabel: "Back tomorrow, 8:00 AM",
    modifierGroupIds: ["mg-spice", "mg-chutney"],
    sortOrder: 7,
    rating: { average: 4.3, count: 71 },
  },

  // ---------------------------------------------------------------- Biryani
  {
    id: "dish-chicken-biryani",
    slug: "hyderabadi-chicken-dum-biryani",
    name: "Hyderabadi Chicken Dum Biryani",
    shortDescription: "Sealed handi, aged basmati, bone-in chicken",
    description:
      "Marinated overnight in yoghurt, fried onion and green chilli, then layered raw with half-cooked basmati and sealed under dough. Forty minutes on dum. Served with raita and mirchi ka salan.",
    categorySlug: "biryani",
    imageUrl: null,
    dietaryType: "NON_VEG",
    spiceLevel: "SPICY",
    tags: ["BESTSELLER", "CHEFS_SPECIAL"],
    basePriceCents: 1690,
    compareAtPriceCents: 1890,
    servesPax: 1,
    calories: 742,
    allergens: ["Dairy", "Cashew"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: BIRYANI_MODS,
    sortOrder: 0,
    rating: { average: 4.9, count: 903 },
  },
  {
    id: "dish-mutton-biryani",
    slug: "mutton-dum-biryani",
    name: "Mutton Dum Biryani",
    shortDescription: "Kid goat on the bone, cooked down to the marrow",
    description:
      "The same dum method, given longer. Shoulder and shank on the bone, so the rice underneath takes on the fat.",
    categorySlug: "biryani",
    imageUrl: null,
    dietaryType: "NON_VEG",
    spiceLevel: "SPICY",
    tags: ["CHEFS_SPECIAL"],
    basePriceCents: 1990,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 815,
    allergens: ["Dairy", "Cashew"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: BIRYANI_MODS,
    sortOrder: 1,
    rating: { average: 4.8, count: 517 },
  },
  {
    id: "dish-veg-biryani",
    slug: "vegetable-dum-biryani",
    name: "Vegetable Dum Biryani",
    shortDescription: "Seasonal vegetables, saffron, fried onion",
    description:
      "Not an afterthought — the vegetables are fried separately so they hold their shape under the dum rather than collapsing into the rice.",
    categorySlug: "biryani",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "MEDIUM",
    tags: ["JAIN_AVAILABLE"],
    basePriceCents: 1390,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 634,
    allergens: ["Dairy", "Cashew"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: BIRYANI_MODS,
    sortOrder: 2,
    rating: { average: 4.6, count: 288 },
  },
  {
    id: "dish-prawn-biryani",
    slug: "prawn-biryani",
    name: "Prawn Biryani",
    shortDescription: "Tiger prawns, folded in at the last layer",
    description:
      "Added late so they steam rather than stew. Lighter on the masala than the chicken, to let the prawn through.",
    categorySlug: "biryani",
    imageUrl: null,
    dietaryType: "NON_VEG",
    spiceLevel: "MEDIUM",
    tags: ["NEW"],
    basePriceCents: 1890,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 688,
    allergens: ["Shellfish", "Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: BIRYANI_MODS,
    sortOrder: 3,
    rating: { average: 4.7, count: 112 },
  },
  {
    id: "dish-egg-biryani",
    slug: "egg-biryani",
    name: "Egg Biryani",
    shortDescription: "Two halved eggs, fried onion, mint",
    description: "The everyday order. Same rice, same dum, lighter on the wallet.",
    categorySlug: "biryani",
    imageUrl: null,
    dietaryType: "EGG",
    spiceLevel: "MEDIUM",
    tags: [],
    basePriceCents: 1450,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 612,
    allergens: ["Egg", "Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: BIRYANI_MODS,
    sortOrder: 4,
    rating: { average: 4.5, count: 164 },
  },

  // ---------------------------------------------------------------- Curries
  {
    id: "dish-chettinad-chicken",
    slug: "chettinad-chicken",
    name: "Chettinad Chicken",
    shortDescription: "Roasted spice masala, black pepper, coconut",
    description:
      "The masala is dry-roasted and ground to order — star anise, marathi moggu, fennel and a great deal of black pepper. Thick rather than saucy.",
    categorySlug: "curries",
    imageUrl: null,
    dietaryType: "NON_VEG",
    spiceLevel: "EXTRA_SPICY",
    tags: ["BESTSELLER"],
    basePriceCents: 1650,
    compareAtPriceCents: null,
    servesPax: 2,
    calories: 528,
    allergens: [],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: CURRY_MODS,
    sortOrder: 0,
    rating: { average: 4.8, count: 344 },
  },
  {
    id: "dish-kadai-paneer",
    slug: "kadai-paneer",
    name: "Kadai Paneer",
    shortDescription: "House paneer, capsicum, crushed coriander seed",
    description:
      "Paneer set in-house each morning. Cooked fast in a kadai so the peppers keep their bite.",
    categorySlug: "curries",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "MEDIUM",
    tags: ["CONTAINS_DAIRY"],
    basePriceCents: 1450,
    compareAtPriceCents: null,
    servesPax: 2,
    calories: 486,
    allergens: ["Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: CURRY_MODS,
    sortOrder: 1,
    rating: { average: 4.6, count: 259 },
  },
  {
    id: "dish-malabar-fish-curry",
    slug: "malabar-fish-curry",
    name: "Malabar Fish Curry",
    shortDescription: "Seer fish, coconut milk, kudampuli",
    description:
      "Soured with kudampuli rather than tamarind, which gives it the smoky edge. Finished in a clay pot.",
    categorySlug: "curries",
    imageUrl: null,
    dietaryType: "NON_VEG",
    spiceLevel: "MEDIUM",
    tags: ["CHEFS_SPECIAL", "GLUTEN_FREE"],
    basePriceCents: 1790,
    compareAtPriceCents: null,
    servesPax: 2,
    calories: 452,
    allergens: ["Fish"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: CURRY_MODS,
    sortOrder: 2,
    rating: { average: 4.7, count: 176 },
  },
  {
    id: "dish-gongura-mutton",
    slug: "gongura-mutton",
    name: "Gongura Mutton",
    shortDescription: "Andhra sorrel leaf, kid goat, Guntur chilli",
    description:
      "Sour, dark and genuinely hot. The sorrel is cooked down until it disappears into the gravy.",
    categorySlug: "curries",
    imageUrl: null,
    dietaryType: "NON_VEG",
    spiceLevel: "EXTRA_SPICY",
    tags: ["CHEFS_SPECIAL"],
    basePriceCents: 1950,
    compareAtPriceCents: null,
    servesPax: 2,
    calories: 574,
    allergens: [],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: CURRY_MODS,
    sortOrder: 3,
    rating: { average: 4.8, count: 131 },
  },
  {
    id: "dish-dal-tadka",
    slug: "dal-tadka",
    name: "Dal Tadka",
    shortDescription: "Yellow lentils, garlic and cumin tempering",
    description:
      "Toor dal cooked soft, then hit twice with a tempering of ghee, garlic, cumin and dried red chilli.",
    categorySlug: "curries",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "MILD",
    tags: ["JAIN_AVAILABLE"],
    basePriceCents: 1150,
    compareAtPriceCents: null,
    servesPax: 2,
    calories: 342,
    allergens: ["Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: CURRY_MODS,
    sortOrder: 4,
    rating: { average: 4.5, count: 218 },
  },
  {
    id: "dish-avial",
    slug: "avial",
    name: "Avial",
    shortDescription: "Mixed vegetables, coconut, curd, coconut oil",
    description:
      "Kerala's answer to a vegetable stew. Barely spiced, finished raw with coconut oil and curry leaf.",
    categorySlug: "curries",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "MILD",
    tags: ["GLUTEN_FREE", "CONTAINS_DAIRY"],
    basePriceCents: 1250,
    compareAtPriceCents: null,
    servesPax: 2,
    calories: 288,
    allergens: ["Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: CURRY_MODS,
    sortOrder: 5,
    rating: { average: 4.4, count: 88 },
  },

  // -------------------------------------------------------- Breads and rice
  {
    id: "dish-butter-naan",
    slug: "butter-naan",
    name: "Butter Naan",
    shortDescription: "Tandoor-baked, brushed with butter",
    description: "Straight off the tandoor wall, brushed while still blistering.",
    categorySlug: "breads",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: ["CONTAINS_DAIRY"],
    basePriceCents: 350,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 262,
    allergens: ["Gluten", "Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-bread-qty"],
    sortOrder: 0,
    rating: null,
  },
  {
    id: "dish-garlic-naan",
    slug: "garlic-naan",
    name: "Garlic Naan",
    shortDescription: "Crushed garlic, coriander, butter",
    description: "Garlic pressed into the dough before baking, not scattered after.",
    categorySlug: "breads",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: ["BESTSELLER", "CONTAINS_DAIRY"],
    basePriceCents: 420,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 281,
    allergens: ["Gluten", "Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-bread-qty"],
    sortOrder: 1,
    rating: { average: 4.7, count: 402 },
  },
  {
    id: "dish-malabar-paratha",
    slug: "malabar-paratha",
    name: "Malabar Paratha",
    shortDescription: "Layered, flaky, pulled by hand",
    description: "Laminated the slow way and slapped between the palms before serving.",
    categorySlug: "breads",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: [],
    basePriceCents: 380,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 318,
    allergens: ["Gluten"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-bread-qty"],
    sortOrder: 2,
    rating: { average: 4.6, count: 173 },
  },
  {
    id: "dish-appam",
    slug: "appam",
    name: "Appam",
    shortDescription: "Two hoppers — lacy edge, soft centre",
    description: "Fermented with toddy-style yeast, cooked in a curved pan.",
    categorySlug: "breads",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: ["GLUTEN_FREE"],
    basePriceCents: 450,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 224,
    allergens: [],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: [],
    sortOrder: 3,
    rating: { average: 4.5, count: 94 },
  },

  // --------------------------------------------------------------- Desserts
  {
    id: "dish-gulab-jamun",
    slug: "gulab-jamun",
    name: "Gulab Jamun",
    shortDescription: "Two, warm, in cardamom syrup",
    description: "Khoya dumplings fried dark and rested in syrup until they drink it up.",
    categorySlug: "desserts",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: ["BESTSELLER", "CONTAINS_DAIRY"],
    basePriceCents: 550,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 386,
    allergens: ["Dairy", "Gluten"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: [],
    sortOrder: 0,
    rating: { average: 4.7, count: 311 },
  },
  {
    id: "dish-mysore-pak",
    slug: "mysore-pak",
    name: "Mysore Pak",
    shortDescription: "Gram flour and ghee, cut thick",
    description:
      "Made in small batches twice a day because it is only worth eating in the first few hours.",
    categorySlug: "desserts",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: ["CHEFS_SPECIAL", "GLUTEN_FREE", "CONTAINS_DAIRY"],
    basePriceCents: 590,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 428,
    allergens: ["Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: [],
    sortOrder: 1,
    rating: { average: 4.9, count: 152 },
  },
  {
    id: "dish-payasam",
    slug: "semiya-payasam",
    name: "Semiya Payasam",
    shortDescription: "Vermicelli, milk, cardamom, cashew and raisin",
    description: "Served warm. Thinner than a kheer, deliberately.",
    categorySlug: "desserts",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: ["CONTAINS_NUTS", "CONTAINS_DAIRY"],
    basePriceCents: 650,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 342,
    allergens: ["Dairy", "Cashew", "Gluten"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-sweetness"],
    sortOrder: 2,
    rating: { average: 4.5, count: 108 },
  },
  {
    id: "dish-rava-kesari",
    slug: "rava-kesari",
    name: "Rava Kesari",
    shortDescription: "Semolina, saffron, ghee, cashew",
    description: "Dense and buttery, scooped warm from the pan.",
    categorySlug: "desserts",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: ["CONTAINS_NUTS", "CONTAINS_DAIRY"],
    basePriceCents: 590,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 398,
    allergens: ["Dairy", "Cashew", "Gluten"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-sweetness"],
    sortOrder: 3,
    rating: { average: 4.4, count: 76 },
  },

  // -------------------------------------------------------------- Beverages
  {
    id: "dish-filter-coffee",
    slug: "filter-coffee",
    name: "Filter Kaapi",
    shortDescription: "Chicory blend, decoction-brewed, pulled by hand",
    description:
      "Brewed overnight in a traditional steel filter and pulled between tumbler and davara until it froths.",
    categorySlug: "beverages",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: ["BESTSELLER", "CONTAINS_DAIRY"],
    basePriceCents: 380,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 112,
    allergens: ["Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-sweetness"],
    sortOrder: 0,
    rating: { average: 4.9, count: 588 },
  },
  {
    id: "dish-masala-chai",
    slug: "masala-chai",
    name: "Masala Chai",
    shortDescription: "Ginger, cardamom, clove, boiled with milk",
    description: "Boiled rather than steeped, the way it should be.",
    categorySlug: "beverages",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: ["CONTAINS_DAIRY"],
    basePriceCents: 350,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 98,
    allergens: ["Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-sweetness"],
    sortOrder: 1,
    rating: { average: 4.6, count: 274 },
  },
  {
    id: "dish-mango-lassi",
    slug: "mango-lassi",
    name: "Mango Lassi",
    shortDescription: "Alphonso pulp, thick curd, no syrup",
    description: "Made with fruit pulp rather than cordial, which is why it is not neon.",
    categorySlug: "beverages",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: ["CONTAINS_DAIRY", "GLUTEN_FREE"],
    basePriceCents: 620,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 248,
    allergens: ["Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-sweetness"],
    sortOrder: 2,
    rating: { average: 4.7, count: 196 },
  },
  {
    id: "dish-neer-mor",
    slug: "neer-mor",
    name: "Neer Mor",
    shortDescription: "Spiced buttermilk, ginger, curry leaf, asafoetida",
    description: "Salty rather than sweet, and the best thing on this list after a Chettinad.",
    categorySlug: "beverages",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "MILD",
    tags: ["GLUTEN_FREE", "CONTAINS_DAIRY"],
    basePriceCents: 390,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 62,
    allergens: ["Dairy"],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: [],
    sortOrder: 3,
    rating: { average: 4.5, count: 84 },
  },
  {
    id: "dish-lime-soda",
    slug: "fresh-lime-soda",
    name: "Fresh Lime Soda",
    shortDescription: "Lime, soda, salt or sugar — your call",
    description: "Pressed to order.",
    categorySlug: "beverages",
    imageUrl: null,
    dietaryType: "VEG",
    spiceLevel: "NONE",
    tags: ["GLUTEN_FREE"],
    basePriceCents: 450,
    compareAtPriceCents: null,
    servesPax: 1,
    calories: 88,
    allergens: [],
    isAvailable: true,
    unavailableUntilLabel: null,
    modifierGroupIds: ["mg-sweetness"],
    sortOrder: 4,
    rating: null,
  },
];

export const MENU_DOCUMENT: MenuDocument = {
  outletId: "outlet-little-india",
  outletName: "India Gate — Little India",
  currency: "SGD",
  generatedAt: "2026-08-30T02:00:00.000Z",
  categories: CATEGORIES,
  dishes: DISHES,
  modifierGroups: MODIFIER_GROUPS,
};
